#!/usr/bin/env python
# -*- coding: utf-8 -*-

################################################################################
# Copyright 2018 ROBOTIS CO., LTD.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
################################################################################

# Author: Leon Jung, Gilbert

import rospy
import numpy as np
from enum import Enum
from std_msgs.msg import UInt8
## from turtlebot3_msgs.msg import movingParam

class CoreModeDecider():
    def __init__(self):
        # subscribes : invoking object detected
        self.sub_traffic_sign = rospy.Subscriber('/detect/traffic_sign', UInt8, self.cbInvokedByTrafficSign, queue_size=1)
        self.sub_traffic_light = rospy.Subscriber('/detect/traffic_light', UInt8, self.cbInvokedByTrafficLight, queue_size=1)
        self.sub_traffic_line = rospy.Subscriber('/detect/traffic_line', UInt8, self.cbInvokedByTrafficLine, queue_size=1)
        self.sub_returned_mode = rospy.Subscriber('/core/returned_mode', UInt8, self.cbReturnedMode, queue_size=1)

        self.pub_debug = rospy.Publisher('/core/debug', UInt8, queue_size = 1)
        # self.pub_moving = rospy.Publisher('/control/moving/state', movingParam, queue_size= 1)
        # publishes : decided mode
        self.pub_decided_mode = rospy.Publisher('/core/decided_mode', UInt8, queue_size=1)

        self.InvokedObject = Enum('InvokedObject', 'traffic_sign traffic_light traffic_line')
        self.TrafficSign = Enum('TrafficSign', 'divide stop parking tunnel left right no_entry construction')
        self.CurrentMode = Enum('CurrentMode', 'idle lane_following traffic_light parking_lot level_crossing tunnel construction')

        self.fnInitMode()
        self.fnInitSelf()


    # Invoke if traffic sign is detected
    def cbInvokedByTrafficSign(self, traffic_sign_type_msg):
        rospy.loginfo("invoke sign")
        if traffic_sign_type_msg.data != self.TrafficSign.parking.value:
            self.fnDecideMode(self.InvokedObject.traffic_sign.value, traffic_sign_type_msg)
            rospy.loginfo("Traffic sign detected")
        else:
            rospy.loginfo("fuck parking")
    # Invoke if traffic light is detected
    def cbInvokedByTrafficLight(self, traffic_light_type_msg):
        rospy.loginfo("invoke light")
        self.fnDecideMode(self.InvokedObject.traffic_light.value, traffic_light_type_msg)
        rospy.loginfo("Traffic light detected")
    
    def cbInvokedByTrafficLine(self, traffic_line_type_msg):
        rospy.loginfo("invoke line")
        self.fnDecideMode(self.InvokedObject.traffic_line.value, traffic_line_type_msg)
        rospy.loginfo("Traffic line detected")

    def cbReturnedMode(self, mode):
        rospy.loginfo("Init Mode")
        self.fnInitMode()

    def fnInitMode(self):                                                   # starts only when the program is started initially or any mission is completed
        self.current_mode = self.CurrentMode.lane_following.value
        self.fnPublishMode()

    def fnInitSelf(self):
        rospy.loginfo("A")
        self.current_mode = self.CurrentMode.traffic_light.value
        rospy.loginfo("A")

    def fnDecideMode(self, invoked_object, msg_data):                       # starts only when the traffic sign / traffic light is detected & current_mode is lane_following
        rospy.loginfo("number 0")
        if self.current_mode == self.CurrentMode.lane_following.value:
            rospy.loginfo("number 1")
            if invoked_object == self.InvokedObject.traffic_light.value:    # Traffic Light detected
                rospy.loginfo("number 2")
                self.current_mode = self.CurrentMode.traffic_light.value
                
            if invoked_object == self.InvokedObject.traffic_sign.value:   # Any Sign detected
                rospy.loginfo("number 3")
                if msg_data.data == self.TrafficSign.stop.value:            # Stop Sign detected
                    rospy.loginfo("number 4")
                    self.current_mode = self.CurrentMode.level_crossing.value
                elif msg_data.data == self.TrafficSign.parking.value:       # Parking Sign detected
                    rospy.loginfo("number 5")
                    self.current_mode = self.CurrentMode.parking_lot.value
                elif msg_data.data == self.TrafficSign.tunnel.value:        # Tunnel Sign detected
                    rospy.loginfo("number 6")
                    self.current_mode = self.CurrentMode.tunnel.value
                # elif msg_data.data == self.TrafficSign.left.value:          # left sign dete
                #     rospy.loginfo("left_sign")
                    # msg_moving = movingParam()s
                    # msg_moving.moving_type=4
                    # msg_moving.moving_value_angular=0.0
                    # msg_moving.moving_value_linear=0.0
                    # self.pub_moving.publish(msg_moving)
                    # self.current_mode = self.CurrentMode.left.value
                elif msg_data.data == self.TrafficSign.right.value:
                    rospy.loginfo("right_sign")
                elif msg_data.data == self.TrafficSign.no_entry.value:
                    rospy.loginfo("no_entry")
                elif msg_data.data == self.TrafficSign.construction.value:
                    rospy.loginfo("construction")
                    self.current_mode = self.CurrentMode.construction.value
                
            else:
                pass

            self.fnPublishMode()

        elif self.current_mode == self.CurrentMode.traffic_light.value:
            rospy.loginfo("number 7")
            if invoked_object == self.InvokedObject.traffic_line.value:
                self.current_mode = self.CurrentMode.lane_following.value
                rospy.loginfo("GO TO HELL")
                self.fnPublishMode()
            
        
        else:
            pass

    def fnPublishMode(self):
        decided_mode = UInt8()
        decided_mode.data = self.current_mode
        self.pub_decided_mode.publish(decided_mode)

    def main(self):
        rospy.spin()

if __name__ == '__main__':
    rospy.init_node('core_mode_decider')
    node = CoreModeDecider()
    node.main()
